kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-demo
  namespace:
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.6.0",
        "id": "f5-hello-world-as3",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
        "AS3": {
            "class": "Tenant",
            "MyApps": {
                "class": "Application",
                "template": "generic",
                "f5_hello_world_as3": {
                    "class": "Service_TCP",
                    "virtualAddresses": [
                        "10.1.10.180"
                    ],
                    "remark": "ingress: f5demo.tcp.v1",
                    "virtualPort": 80,
                    "pool": "helloworld_pool"
                },
                "helloworld_pool": {
                    "class": "Pool",
                    "monitors": [
                        "tcp"
                    ],
                    "members": [
                        {
                            "servicePort": 8080,
                            "serverAddresses": []
                        }
                    ]
                }
             }
        }
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "AS3kubeDataCenter": {
                    "class": "GSLB_Data_Center"
                },
                "testServer": {
                    "class": "GSLB_Server",
                    "dataCenter": {
                        "use": "AS3kubeDataCenter"
                    },
                    "devices": [
                        {
                            "address": "10.1.10.10"
                        }
                    ],
                    "virtualServerDiscoveryMode": "enabled-no-delete",
                    "exposeRouteDomainsEnabled": true
                }
            }
        }

     }
     }
