kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-demo
  namespace:
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "f5demo",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "kubedns_pool": {
                    "class": "GSLB_Pool",
                    "members": [
                        {
                            "ratio": 10,
                            "server": {
                                "use": "/Common/testServer"
                            },
                            "virtualServer": "0"
                        }
                    ],
                    "monitors": [
                        {
                            "bigip": "/Common/http"
                        }
                    ],
                    "resourceRecordType": "A"
                }
            }
        }
    }
    }
