kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: kube-system
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id":"f5-hello-world-as3",
        "label":"Sample AS3 Template",
        "remark": "Remove AS3 declaration",
        "MyApps": {
          "class": "Tenant"
        }
      }
    }
